//
//  FFmpegSubtitleParse.swift
//  KSPlayer
//
//  RE source: Forward v1.3.15 — SubtitleParseRegistry fallback parser
//  Fallback parser registered last in the five-parser registry
//  [AssImageParse, AssParse, VTTParse, SrtParse, FFmpegSubtitleParse]. Also the
//  carrier for the SRT→ASS bridge (and, via that bridge, LRC support): it builds
//  a complete ASS document out of SRT cue data so the resulting subtitle can be
//  rendered through the libass / ASS path.
//

import Foundation

/// Fallback `KSParseProtocol` implementation and SRT→ASS document builder.
///
/// Registered last in the parse chain (`[AssImageParse, AssParse, VTTParse,
/// SrtParse, FFmpegSubtitleParse]`), so the protocol witnesses below are reached
/// only after the text-based parsers decline. Its load-bearing member is
/// ``convertSrtToAss(_:)``, which the renderer pipeline
/// (`AssIncrementImageRenderer.composeFrame`) uses to turn SRT data into a full
/// ASS document for libass.
public class FFmpegSubtitleParse: KSParseProtocol {
    public init() {}

    /// Protocol witness. As the last parser in the registry this is a thin
    /// "accept the remainder" wrapper — the substantive work for this type is
    /// ``convertSrtToAss(_:)``, not scanner-based parsing.
    public func canParse(scanner: Scanner) -> Bool {
        !scanner.isAtEnd
    }

    /// Protocol witness. The binary's `FFmpegSubtitleParse` does not implement a
    /// scanner-driven `parsePart`; its real entry point is the SRT→ASS document
    /// builder ``convertSrtToAss(_:)``. Kept as a no-op wrapper to satisfy
    /// `KSParseProtocol`.
    public func parsePart(scanner: Scanner) -> SubtitlePart? {
        nil
    }

    // MARK: - SRT → ASS document builder

    /// ASS document preamble: `[Script Info]` plus the `[V4+ Styles]` `Format:`
    /// line. The `buildDefaultStyleHeader` `Style:` line is appended after this,
    /// then ``eventsHeader``.
    ///
    /// RE: string constant @ 0x10333c860 (1.3.15), appended verbatim by
    /// `convertSrtToAss`.
    private static let scriptInfoHeader = """
    [Script Info]
    Script generated by KSPlayer
    ScriptType: v4.00+
    PlayResX: 384
    PlayResY: 216
    WrapStyle: 3
    ScaledBorderAndShadow: yes
    YCbCr Matrix: None

    [V4+ Styles]
    Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
    """

    /// `[Events]` section header (blank-line separated), appended after the
    /// `[V4+ Styles]` `Style:` line and before the `Dialogue:` lines.
    ///
    /// RE: string constant @ 0x10333ca00 (1.3.15).
    private static let eventsHeader = """


    [Events]
    Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
    """

    /// Fixed middle columns of every emitted `Dialogue:` line:
    /// `,Default,,0,0,0,,` — Style="Default", empty Name, zero MarginL/R/V, empty
    /// Effect — sitting between the `End` timestamp and the cue `Text`.
    ///
    /// RE: string constant @ 0x10333ca60 (1.3.15).
    private static let dialogueStyleColumns = ",Default,,0,0,0,,"

    /// ASS hard line break. The binary rewrites each newline inside a cue body to
    /// `\N` before emitting the `Dialogue:` line (ASS treats a raw newline as a
    /// cue terminator, so multi-line cues must use `\N`).
    private static let assLineBreak = "\\N"

    /// Build a complete ASS document from SRT data.
    ///
    /// Pipeline (each binary step preserved as a separate call):
    ///  1. Append the `[Script Info]` + `[V4+ Styles]` `Format:` boilerplate.
    ///  2. Append `SrtParse.buildDefaultStyleHeader()` (the `Style: Default,…` line).
    ///  3. Append the `[Events]` section header.
    ///  4. Drive an SRT scanner cue-by-cue with `SrtParse.parseEntry`; for each cue
    ///     rewrite embedded newlines to `\N`, strip residual HTML tags with
    ///     `SrtParse.cleanupTags`, and check for `<c>` colour tags
    ///     (word constant `0x3e633c3e`).
    ///     - No `<c>`: emit one `Dialogue: 0,{start},{end},Default,,0,0,0,,{text}` line
    ///       using the cue's text as a UTF-8 C-string for libass.
    ///     - Has `<c>`: split into coloured runs via
    ///       `AssParse.processStyleOverrideTags` and emit one `Dialogue:` line per
    ///       run (each over the cue's start/end), again UTF-8 C-string encoded.
    ///
    /// RE: 0x101480414 (FFmpegSubtitleParse.convertSrtToAss, 1.3.15, 1484B,
    /// 2 xrefs from AssIncrementImageRenderer.composeFrame). Builds the libass
    /// input from an SRT source; carrier for SRT→ASS and LRC support.
    public func convertSrtToAss(_ srt: String) -> String {
        let srtParse = SrtParse()

        // (1)–(3) Document header: Script Info + V4+ Styles + default style + Events.
        var document = FFmpegSubtitleParse.scriptInfoHeader
        document += srtParse.buildDefaultStyleHeader()
        document += FFmpegSubtitleParse.eventsHeader

        // (4) Cue loop. `parseEntry` advances the scanner to the next `-->` line,
        // normalises the millisecond separator, and returns the cue body; it
        // yields nil at EOF, ending the loop.
        let scanner = Scanner(string: srt)
        scanner.charactersToBeSkipped = nil
        while !scanner.isAtEnd {
            guard let entry = srtParse.parseEntry(scanner: scanner) else {
                break
            }

            // Rewrite raw newlines to the ASS hard break, then strip any leftover
            // HTML tags. These two steps mirror the binary's per-cue preprocessing.
            let unwrapped = entry.text.replacingOccurrences(
                of: "\n",
                with: FFmpegSubtitleParse.assLineBreak
            )
            let cleaned = srtParse.cleanupTags(unwrapped)

            if cleaned.contains("<c>") {
                // Coloured cue: one Dialogue line per `<c>…</c>` run. The segments
                // carry style + content only, so every run uses the cue's start/end.
                let segments = AssParse().processStyleOverrideTags(cleaned)
                for segment in segments {
                    document += FFmpegSubtitleParse.dialogueLine(
                        start: entry.start,
                        end: entry.end,
                        text: segment.content
                    )
                }
            } else {
                // Plain cue: a single Dialogue line.
                document += FFmpegSubtitleParse.dialogueLine(
                    start: entry.start,
                    end: entry.end,
                    text: cleaned
                )
            }
        }

        return document
    }

    /// Assemble one `Dialogue: 0,{start},{end},Default,,0,0,0,,{text}\n` line.
    ///
    /// The binary passes the cue text through `String.utf8CString` /
    /// `String(cString:)` before appending (a libass round-trip that also drops a
    /// trailing NUL); the reconstruction appends the Swift `String` directly,
    /// which is observably equivalent for valid UTF-8 cue text.
    ///
    /// RE: inlined in 0x101480414 — `Dialogue: 0,` + start + `,` + end +
    /// `,Default,,0,0,0,,` + cString(text) + `\n`.
    private static func dialogueLine(start: String, end: String, text: String) -> String {
        "Dialogue: 0,\(start),\(end)\(dialogueStyleColumns)\(text)\n"
    }
}
